_target_: src.models.mnist_gan_model.MNISTGANModel

lr: 0.0002
b1: 0.5
b2: 0.999
n_classes: 10
latent_dim: 100
channels: 1
img_size: 32

# TODO: instantiate the generator and discriminator objects with Hydra
#       https://hydra.cc/docs/advanced/instantiate_objects/overview/
generator:
  _target_: src.models.modules.generators.Generator
  n_classes: ${..n_classes}
  latent_dim: ${..latent_dim}
  channels: ${..channels}
  img_size: ${..img_size}

discriminator:
  _target_: src.models.modules.discriminators.Discriminator
  n_classes: ${..n_classes}
  channels: ${..channels}
  img_size: ${..img_size}
